tasks:
  - init: pip install -r completed-spaceflights/src/requirements.txt
    command: cd jupyter-spaceflights jupyter lab --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    name: jupyter

ports:
  - port: 8888
    onOpen: notify
